### ISSUE TITLE
Ошибки при подключении

### ISSUE THREAD

**Issue by DevAzbn** [antixrist/node-phpmorphy#1]
Подключил мерфи, обновил версию Node.js, вебпака и бабеля нет
Выдает следующую ошибку

module.js:471
    throw err;
    ^

Error: Cannot find module 'core-js/modules/es6.map'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\project\x\node_modules\phpmorphy\build\index.js:8599:18)
    at __webpack_require__ (D:\project\x\node_modules\phpmorphy\build\index.js:21:30)
    at Object.module.exports.Object.defineProperty.value (D:\project\x\node_modules\phpmorphy\build\index.js:5
554:1)
    at __webpack_require__ (D:\project\x\node_modules\phpmorphy\build\index.js:21:30)
    at Object.<anonymous> (D:\project\x\node_modules\phpmorphy\build\index.js:8579:18)
    at __webpack_require__ (D:\project\x\node_modules\phpmorphy\build\index.js:21:30)

**Comment by antixrist** [comment]
Приветствую!

Вебпак и бабель подтянутся автоматически, из зависимостей.

Какая версия npm? (```npm -v```)
Устанавливали в чистый проект или в существующий?
npm-shrinkwrap использовался?

Эта ошибка возникает из-за того, что:
а) babel-polyfill по какой-либо причине не установился;
б) npm shrinkwrap не вытащил babel-polyfill на верхний уровень в папке node_modules;
в) т.к. пакет phpmorphy сам по себе довольно тяжёлый, то в процессе скачивания и установки могли произойти обрывы связи (или что-то подобное) и что-нибудь могло пойти не так и зависимости не доустановились. У меня такое бывало.

Гадать могу долго. Лучше попробуйте установить морфер в чистый проект и, если ошибка повторится:
а) напишите последовательность шагов для воспроизведения и используемые версии ноды/npm;
б) переходите на [yarn](https://yarnpkg.com/en/docs/install)! И вместо:
```npm install --save-dev phpmorphy```
используйте вот это:
```yarn add phpmorphy```

С yarn'ом таких проблем быть не должно

**Comment by antixrist** [comment]
> Вебпак и бабель подтянутся автоматически, из зависимостей.

Хотя о чём это я - они не подтянутся, потому что они в devDependencies. Для использования они (на данный момент) и не нужны. Автоматически должны установиться только вот [эти](https://github.com/antixrist/node-phpmorphy/blob/af0d1017b041038c4a28d53bef1d00717df26bbc/package.json#L12-L16).

**Comment by DevAzbn** [comment]
Да, действительно что-то не так встало. На другом компе все заработало сразу. Спасибо за реализацию)

**Comment by antixrist** [comment]
Не за что!

На данный момент [протестированы](https://github.com/antixrist/node-phpmorphy/blob/master/src/tests/index.js#L567) русский и английский языки. В остальных у меня нужды пока не было.
Если будут ошибки или какое-нибудь не документированное поведение - смело пишите!
