### ISSUE TITLE
Error: Cannot find module 'source-map-support'

### ISSUE THREAD

**Issue by Ti-webdev** [antixrist/node-phpmorphy#3]
```
Error: Cannot find module 'source-map-support'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../phpmorphy/build/index.js:1:63)
```
source-map-support это пропущенная зависимость?

**Comment by antixrist** [comment]
@Ti-webdev получается, что да. пофиксил https://github.com/antixrist/node-phpmorphy/commit/6a46cdc13141ad9cc6912d68c0c1e80c8d7bbedc
